import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="h-screen p-5 bg-gray-800 text-white">
      <h1 className="text-6xl mb-5">Homepage</h1>
      <p className="text-xl mb-8">
        This project was generated by{" "}
        <a href="https://www.dhiwise.com" className="text-blue-300 hover:text-blue-400 no-underline">
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul className="list-none p-0">
        <li className="mb-2.5">
          <Link to="/roomsframe" className="text-blue-300 hover:text-blue-400 no-underline">
            Roomsframe
          </Link>
        </li>
        <li className="mb-2.5">
          <Link to="/createnewroom" className="text-blue-300 hover:text-blue-400 no-underline">
            Createnewroom
          </Link>
        </li>
        <li className="mb-2.5">
          <Link to="/messagesframe" className="text-blue-300 hover:text-blue-400 no-underline">
            Messagesframe
          </Link>
        </li>
        <li className="mb-2.5">
          <Link to="/settingsframe" className="text-blue-300 hover:text-blue-400 no-underline">
            Settingsframe
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
